apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 3
  selector:
     matchLabels:
       app: ArtifactStateCluster
  template:
    metadata:
      labels:
        app: ArtifactStateCluster
        tag: clusternode
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9001'
    spec:
      serviceAccountName: nodes-sa
      containers:
      - name: node
        image: localhost:32000/akka-typed-blog-distributed-state/cluster:latest
        #health
        readinessProbe:
          httpGet:
            path: /ready
            port: akka-mgmt-http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: akka-mgmt-http
          initialDelaySeconds: 90
          periodSeconds: 30
        #health
        env:
        - name: HOSTNAME
          valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        - name: DB_HOST_DC1
          value: "yugabyte-db-dc2" # Service Name of Egress
        - name: APP-VERSION
          value: "0.1.21"
        - name: DATA-CENTER
          value: "dc2"
        - name: ALL-DATA-CENTERS
          value: "dc1,dc2"
        - name: QUERY_PLUGIN_ID
          value: "akka.persistence.r2dbc.query"
        - name: SNAPSHOT_ON_NR_EVENTS
          value: "5"
        - name: KEEP_N_SNAPSHOTS
          value: "3"
        - name: JAVA_OPTS
          value: "-Dconfig.resource=cluster-application-k8s-multi-dc.conf"
        - name: JAVA_TOOL_OPTIONS
          value: "-Dconfig.resource=cluster-application-k8s-multi-dc.conf"
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
        - name: node-metrics
          containerPort: 9001
      restartPolicy: Always

