version: '3.3'

# Local Yugabyte database, see https://docs.yugabyte.com/latest/deploy/docker/docker-compose/

volumes:
  yb-master-data-1:
  yb-tserver-data-1:

services:
  yb-master:
    image: yugabytedb/yugabyte:2.12.2.0-b58
    container_name: yb-master-n1
    volumes:
      - yb-master-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-master-n1:7100",
               "--rpc_bind_addresses=yb-master-n1:7100",
               "--replication_factor=1"]
    ports:
      - "7000:7000"
    environment:
      SERVICE_7000_NAME: yb-master
    networks:
      - statepoc

  yb-tserver:
    image: yugabytedb/yugabyte:2.12.2.0-b58
    container_name: yb-tserver-n1
    shm_size: '512mb'
    volumes:
      - yb-tserver-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--start_pgsql_proxy",
               "--rpc_bind_addresses=yb-tserver-n1:9100",
               "--tserver_master_addrs=yb-master-n1:7100",
               "--ysql_sequence_cache_minval=1",
               "--yb_num_shards_per_tserver=1"]
    ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - yb-master
    networks:
      - statepoc

  cluster:
    image: akka-typed-blog-distributed-state/cluster:0.1.4
    deploy:
      replicas: 3
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker-dns.conf"
      CLUSTER_IP: cluster
      DB_HOST: yb-tserver
      CINNAMON_ELASTIC_HOSTS: elasticsearch:9200
    networks:
    - cinnamon-elasticsearch-docker-sandbox-2170_sandbox
    - statepoc

  # Note: if you need more than one instance of the endpoint,
  #       you'll need to duplicate, instead of replicas, because of port conflicts
  endpoint:
    image: akka-typed-blog-distributed-state/cluster:0.1.4
    links:
      - cluster
    depends_on:
      - cluster
    environment:
      JAVA_OPTS: "-Dconfig.resource=endpoint-application-docker-dns.conf"
      CLUSTER_IP: endpoint
      CINNAMON_ELASTIC_HOSTS: elasticsearch:9200
    ports:
    - "8082:8082"
    - "8558:8558"
    networks:
    - cinnamon-elasticsearch-docker-sandbox-2170_sandbox
    - statepoc


networks:

  #Note: this network name must match the version of the Telemetry sandbox
  cinnamon-elasticsearch-docker-sandbox-2170_sandbox:
    external: true

  statepoc:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.22.0.0/16

