
services:
  cassandra-db:
    hostname: cassandra-1
    image: cassandra:3.11.11
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    #    volumes:
    #    - ./data/cassandra-1:/var/lib/cassandra:rw
    networks:
      - statepoc
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cluster:
    image: akka-typed-blog-distributed-state/cluster:1.2.0
    deploy:
      replicas: 3
    links:
      - cassandra-db
    #    depends_on:
    #    - cassandra-db
    environment:
      JAVA_OPTS: "-Dconfig.resource=nonsup-cluster-application-docker.conf"
      CLUSTER_IP: cluster
      CASSANDRA_CONTACT_POINT1: cassandra-db:9042
    networks:
      - statepoc

  endpoint:
    image: akka-typed-blog-distributed-state/cluster:1.2.0
    links:
      - cluster
    depends_on:
      - cluster
    environment:
      JAVA_OPTS: "-Dconfig.resource=nonsup-endpoint-application-docker.conf"
      CLUSTER_IP: endpoint
    ports:
      - "8082:8082"
      - "8558:8558"
    networks:
      - statepoc

networks:
  statepoc:
    driver: bridge
