apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app-monitoring: artifactstate
spec:
  type: ClusterIP
  ports:
    - name: akka-mgmt-http
      protocol: TCP
      port: 8558
      targetPort: akka-mgmt-http
    - name: remoting
      protocol: TCP
      port: 2552
      targetPort: remoting
    - name: node-metrics
      port: 9001
      targetPort: node-metrics
  selector:
    tag: clusternode

