apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090

  selector:
    prometheus: artifactstate-svc-monitor