apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-http-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public
  defaultBackend:
    service:
      name: prometheus-k8s
      port:
        number: 9090
  rules:
    - http:
        paths:
          - path: /prometheus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: prometheus-k8s
                port:
                  number: 9090