apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-http-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: prometheus-operated
      port:
        number: 9090